# Generated by Django 5.0 on 2025-08-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='capa',
            field=models.URLField(blank=True, null=True, verbose_name='URL da capa'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='id_tmdb',
            field=models.IntegerField(verbose_name='ID no TMDB'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='sinopse',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Sinopse'),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='streaming',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do streaming'),
        ),
        migrations.AlterField(
            model_name='streaming',
            name='url',
            field=models.URLField(verbose_name='URL do streaming'),
        ),
    ]
