services:
  web:
    build: .
    container_name: django_app
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=meu_banco
      - DB_USER=usuario
      - DB_PASSWORD=senha
      - DB_HOST=db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
