STREAMING_LINKS_BY_NAME = {
    "Apple TV": "https://www.apple.com/apple-tv-plus/",
    "Google Play Movies": "https://play.google.com/store/movies",
    "Fandango At Home": "https://www.fandangonow.com/",
    "Netflix": "https://www.netflix.com/",
    "Amazon Prime Video": "https://www.primevideo.com/",
    "Amazon Video": "https://www.amazon.com/Video",
    "MUBI": "https://mubi.com/",
    "Hulu": "https://www.hulu.com/",
    "NetMovies": "https://www.netmovies.com/",
    "maxdome Store": "https://www.maxdome.de/",
    "Stan": "https://www.stan.com.au/",
    "Fandor": "https://www.fandor.com/",
    "Netzkino": "https://www.netzkino.de/",
    "Sky Go": "https://www.sky.com/go",
    "WOW": "https://wowtv.com/",
    "Alleskino": "https://www.alleskino.de/",
    "MGM Plus": "https://mgmplus.com/",
    "Rakuten TV": "https://rakuten.tv/",
    "BBC iPlayer": "https://www.bbc.co.uk/iplayer",
    "Now TV": "https://www.nowtv.com/",
    "Chili": "https://www.chili.com/",
    "ITVX": "https://www.itv.com/hub/itvx",
    "Starz": "https://www.starz.com/",
    "Looke": "https://www.looke.com.br/",
    "BoxOffice": "https://www.boxoffice.com/",
    "ShowMax": "https://www.showmax.com/",
    "Canal VOD": "https://www.canalvodatv.com/",
    "Bbox VOD": "https://www.bbox-vod.fr/",
    "Orange VOD": "https://vod.orange.fr/",
    "Atres Player": "https://www.atresplayer.com/",
    "Filmin": "https://www.filmin.es/",
    "Filmin Plus": "https://www.filmin.es/plus",
    "Nuestro Cine MX": "https://www.nuestrocine.com.mx/",
    "Pathé Thuis": "https://www.pathe-thuis.nl/",
    "Videoland": "https://www.videoland.com/",
    "Tubi TV": "https://tubitv.com/",
    "Viaplay": "https://viaplay.com/",
    "NBC": "https://www.nbc.com/",
    "AMC": "https://www.amc.com/",
    "10": "https://10play.com.au/",
    "The CW": "https://www.cwtv.com/",
    "U-NEXT": "https://www.video.unext.jp/",
    "Acorn TV": "https://acorn.tv/",
    "Watcha": "https://watcha.com/",
    "Shudder": "https://www.shudder.com/",
    "GuideDoc": "https://www.guidedoc.tv/",
    "Channel 4": "https://www.channel4.com/",
    "Timvision": "https://www.timvision.it/",
    "Infinity+": "https://www.infinityplus.it/",
    "Ivi": "https://www.ivi.ru/",
    "Okko": "https://okko.tv/",
    "Amediateka": "https://www.amediateka.ru/",
    "Kinopoisk": "https://www.kinopoisk.ru/",
    "Amazon Prime Video": "https://www.primevideo.com/",
    "Hotstar": "https://www.hotstar.com/",
    "FXNow": "https://www.fox.com/fxnow/",
    "Bookmyshow": "https://in.bookmyshow.com/movies",
    "Sky Store": "https://www.sky.com/store",
    "SBS On Demand": "https://www.sbs.com.au/ondemand",
    "Videobuster": "https://www.videobuster.de/",
    "Foxtel Now": "https://www.foxtel.com.au/now.html",
    "ABC iview": "https://iview.abc.net.au/",
    "FILMO": "https://www.filmo.tv/",
    "Cineplex": "https://www.cineplex.com/Movies",
    "Sundance Now": "https://www.sundancenow.com/",
    "iciTouTV": "https://ici.tou.tv/",
    "M6+": "https://www.m6plus.fr/",
    "ABC": "https://abc.com/",
    "Movistar Plus+ Ficción Total": "https://www.movistarplus.es/",
    "blue TV": "https://www.bluetv.cl/",
    "BritBox": "https://www.britbox.com/",
    "History": "https://www.history.com/",
    "A&E": "https://www.aetv.com/",
    "Lifetime": "https://www.mylifetime.com/",
    "Viu": "https://www.viu.com/",
    "Catchplay": "https://www.catchplay.com/",
    "iflix": "https://www.iflix.com/",
    "Claro video": "https://www.clarovideo.com/",
    "Netflix Kids": "https://www.netflix.com/browse/genre/783",
    "MagentaTV": "https://www.telekom.com/en/magenta-tv",
    "Hollywood Suite": "https://www.hollywoodsuite.ca/",
    "Screambox": "https://www.screambox.com/",
    "Paramount Pictures": "https://www.paramount.com/",
    "YouTube Premium": "https://www.youtube.com/premium",
    "Curzon Home Cinema": "https://www.curzonhomecinema.com/",
    "Curiosity Stream": "https://curiositystream.com/",
    "Kanopy": "https://www.kanopy.com/",
    "YouTube": "https://www.youtube.com/",
    "AcornTV Amazon Channel": "https://www.amazon.com/acorn-tv",
    "BritBox Amazon Channel": "https://www.amazon.com/britbox",
    "Fandor Amazon Channel": "https://www.amazon.com/fandor",
    "MUBI Amazon Channel": "https://www.amazon.com/mubi",
    "Screambox Amazon Channel": "https://www.amazon.com/screambox",
    "Shudder Amazon Channel": "https://www.amazon.com/shudder",
    "Sundance Now Amazon Channel": "https://www.amazon.com/sundance-now",
    "The Roku Channel": "https://www.roku.com/whats-on/the-roku-channel",
    "PBS": "https://www.pbs.org/",
    "Sky": "https://www.sky.com/",
    "Freeform": "https://www.freeform.com/",
    "Hoopla": "https://www.hoopladigital.com/",
    "ARD Mediathek": "https://www.ardmediathek.de/",
    "Rai Play": "https://www.raiplay.it/",
    "BFI Player": "https://player.bfi.org.uk/",
    "Crave": "https://www.crave.ca/",
    "Zee5": "https://www.zee5.com/",
    "Arte": "https://www.arte.tv/",
    "YouTube Free": "https://www.youtube.com/",
    "France TV": "https://www.france.tv/",
    "Sony Liv": "https://www.sonyliv.com/",
    "Universcine": "https://www.universcine.com/",
    "7plus": "https://7plus.com.au/",
    "ALLBLK": "https://watch.alblk.tv/",
    "fuboTV": "https://www.fubo.tv/",
    "Criterion Channel": "https://www.criterionchannel.com/",
    "WWE Network": "https://www.wwe.com/wwenetwork",
    "History Vault": "https://watch.historyvault.com/",
    "Neon TV": "https://www.neontv.co.nz/",
    "Pure Flix": "https://www.pureflix.com/",
    "Crunchyroll": "https://www.crunchyroll.com/",
    "Lifetime Movie Club": "https://www.lifetimemovieclub.com/",
    "BBC Player Amazon Channel": "https://www.amazon.com/bbc-player",
    "ZDF Herzkino Amazon Channel": "https://www.amazon.com/zdf-herzkino",
    "BFI Player Amazon Channel": "https://www.amazon.com/bfi-player",
    "Cinemax Amazon Channel": "https://www.amazon.com/cinemax",
    "Hallmark+ Amazon Channel": "https://www.amazon.com/hallmark-plus",
    "MZ Choice Amazon Channel": "https://www.amazon.com/mz-choice",
    "PBS Kids Amazon Channel": "https://www.amazon.com/pbs-kids",
    "PBS Masterpiece Amazon Channel": "https://www.amazon.com/pbs-masterpiece",
    "RetroCrush Amazon Channel": "https://www.amazon.com/retrocrush",
    "Ziggo TV": "https://www.ziggogo.tv/",
    "RTL+": "https://www.rtlplus.de/",
    "Pluto TV": "https://pluto.tv/",
    "Joyn": "https://www.joyn.de/",
    "Globoplay": "https://globoplay.globo.com/",
    "Sun Nxt": "https://www.sunnxt.com/",
    "LaCinetek": "https://www.lacinetek.com/",
    "Be TV Go": "https://www.betv.be/",
    "VRT MAX": "https://www.vrt.be/vrtnu/",
    "CBC Gem": "https://gem.cbc.ca/",
    "Hoichoi": "https://www.hoichoi.tv/",
    "Sky X": "https://www.sky.com/x",
    "USA Network": "https://www.usanetwork.com/",
    "Yle Areena": "https://areena.yle.fi/",
    "Cinemas a la Demande": "https://www.cinemasalademande.com/",
    "CTV": "https://www.ctv.ca/",
    "FlixFling": "https://www.flixfling.com/",
    "Fandango at Home Free": "https://www.fandango.com/fandango-at-home",
    "5": "https://www.channel5.com/",
    "Filmtastic Amazon Channel": "https://www.amazon.com/filmtastic",
    "Disney Plus": "https://www.disneyplus.com/",
    "Ruutu": "https://www.ruutu.fi/",
    "MovistarTV": "https://www.movistar.es/television",
    "puhutv": "https://puhutv.com/",
    "Bet+ Amazon Channel": "https://www.amazon.com/betplus",
    "Rakuten Viki": "https://www.viki.com/",
    "Kino on Demand": "https://www.kinoondemand.com/",
    "Apple TV+": "https://www.apple.com/apple-tv-plus/",
    "wavve": "https://www.wavve.com/",
    "DocPlay": "https://www.docplay.com/",
    "Mediaset Infinity": "https://www.mediasetplay.mediaset.it/",
    "NPO Start": "https://www.npostart.nl/",
    "TCM": "https://www.tcm.com/",
    "TNT": "https://www.tntdrama.com/",
    "IndieFlix": "https://www.indieflix.com/",
    "VOD Club": "https://vodclub.com/",
    "Go3": "https://go3.lt/",
    "9Now": "https://www.9now.com.au/",
    "Canal+": "https://www.canalplus.com/",
    "TV 2": "https://tv2.dk/",
    "BINGE": "https://www.binge.com.au/",
    "Peacock Premium": "https://www.peacocktv.com/",
    "Peacock Premium Plus": "https://www.peacocktv.com/",
    "Sooner": "https://www.sooner.com/",
    "wedotv": "https://www.wedotv.com/",
    "FlixOlé": "https://www.flixole.com/",
    "TVNZ+": "https://www.tvnz.co.nz/",
    "Film1": "https://www.film1.nl/",
    "BBC America": "https://www.bbcamerica.com/",
    "Animation Digital Network": "https://www.adnstreaming.com/",
    "Here TV": "https://www.heretv.com/",
    "Joyn Plus": "https://www.joyn.de/",
    "Blockbuster": "https://www.blockbuster.com/",
    "SF Anytime": "https://www.sfanytime.com/",
    "HiDive": "https://www.hidive.com/",
    "TV 2 Play": "https://play.tv2.dk/",
    "Flix Premiere": "https://flixpremiere.com/",
    "OVID": "https://ovid.tv/",
    "OzFlix": "https://www.ozflix.tv/",
    "Draken Films": "https://www.drakenfilms.com/",
    "Fetch TV": "https://www.fetch.com.au/",
    "Hungama Play": "https://www.hungama.com/play/",
    "Chai Flicks": "https://www.chaiflicks.com/",
    "Shout! Factory TV": "https://www.shoutfactorytv.com/",
    "ThreeNow": "https://www.threenow.co.nz/",
    "NFB": "https://www.nfb.ca/",
    "NRK TV": "https://tv.nrk.no/",
    "Filmstriben": "https://www.filmstriben.dk/",
    "Dekkoo": "https://www.dekkoo.com/",
    "Retrocrush": "https://www.retrocrush.tv/",
    "Belas Artes à La Carte": "https://www.belasartesalacarte.com/",
    "Beamafilm": "https://www.beamafilm.com/",
    "Global TV": "https://www.globaltv.com/",
    "Picl": "https://www.picl.nl/",
    "RTPplay": "https://www.rtp.pt/play/",
    "Night Flight Plus": "https://nightflightplus.com/",
    "VIX": "https://vix.com/",
    "RTBF Auvio": "https://www.rtbf.be/auvio/",
    "Kirjastokino": "https://kirjastokino.fi/",
    "Kocowa": "https://www.kocowa.com/",
    "Bioskop Online": "https://www.bioskoponline.com/",
    "DIRECTV GO": "https://www.directvgo.com/",
    "genflix": "https://www.genflix.co.id/",
    "Club Illico": "https://www.clubillico.com/",
    "NLZIET": "https://www.nlziet.nl/",
    "Revry": "https://www.revry.tv/",
    "ShemarooMe": "https://www.shemaroome.com/",
    "DOCSVILLE": "https://www.docsville.com/",
    "EPIC ON": "https://www.epicon.in/",
    "GOSPEL PLAY": "https://www.gospelplay.tv/",
    "Home of Horror": "https://www.homeofhorror.com/",
    "Filmtastic": "https://www.filmtastic.com/",
    "ArthouseCNMA": "https://www.arthousecnma.com/",
    "ManoramaMax": "https://www.manoramamax.com/",
    "MAX Stream": "https://www.maxstream.tv/",
    "Claro tv+": "https://www.clarotv.com/",
    "Spectrum On Demand": "https://www.spectrumondemand.com/",
    "tvo": "https://www.tvo.org/",
    "Vidio": "https://www.vidio.com/",
    "CINE": "https://www.cine.com/",
    "SVT": "https://www.svt.se/",
    "Cineasterna": "https://www.cineasterna.com/",
    "Tele2 Play": "https://www.tele2play.se/",
    "Oldflix": "https://www.oldflix.com/",
    "Tata Play": "https://www.tataplay.com/",
    "Hi-YAH": "https://www.hi-yah.com/",
    "Player": "https://player.pl/",
    "TBS": "https://www.tbs.com/",
    "tru TV": "https://www.trutv.com/",
    "DisneyNOW": "https://disneynow.com/",
    "Discovery+": "https://www.discoveryplus.com/",
    "iWant": "https://www.iwanttfc.com/",
    "Shadowz": "https://www.shadowz.com/",
    "AsianCrush": "https://www.asiancrush.com/",
    "MX Player": "https://www.mxplayer.in/",
    "Noovo": "https://www.noovo.ca/",
    "TriArt Play": "https://www.triartplay.com/",
    "Discovery +": "https://www.discoveryplus.com/",
    "Popcorntimes": "https://www.popcorntimes.com/",
    "Discovery+": "https://www.discoveryplus.com/",
    "Knowledge Network": "https://www.knowledge.ca/",
    "AMC+": "https://www.amcplus.com/",
    "AMC+ Amazon Channel": "https://www.amazon.com/amc-plus",
    "ARROW": "https://www.arrowvideo.com/",
    "Paramount Plus": "https://www.paramountplus.com/",
    "aha": "https://www.aha.video/",
    "Amazon Arthaus Channel": "https://www.amazon.com/arthaus",
    "Argo": "https://www.argo.tv/",
    "ZDF": "https://www.zdf.de/",
    "Plex": "https://www.plex.tv/",
    "Viddla": "https://www.viddla.se/",
    "Elisa Viihde": "https://www.elisa.fi/viihde/",
    "rtve": "https://www.rtve.es/",
    "filmfriend": "https://www.filmfriend.de/",
    "Libreflix": "https://libreflix.org/",
    "WOW Presents Plus": "https://wowpresentsplus.com/",
    "IFFR Unleashed": "https://iffr.com/en/iffr-unleashed",
    "Tenk": "https://www.tenk.no/",
    "Magellan TV": "https://watch.magellantv.com/",
    "QFT Player": "https://player.qft.ie/",
    "Telia Play": "https://www.telia.fi/play",
    "BroadwayHD": "https://www.broadwayhd.com/",
    "More TV": "https://www.more.tv/",
    "Filmzie": "https://www.filmzie.com/",
    "Filmoteket": "https://www.filmoteket.no/",
    "Lionsgate Play": "https://www.lionsgateplay.com/",
    "MovieSaints": "https://www.moviesaints.com/",
    "KPN": "https://www.kpn.com/television.htm",
    "True Story": "https://www.truestorychannel.com/",
    "DocAlliance Films": "https://www.docalliancefilms.com/",
    "Premier": "https://www.premier.org/",
    "RTL Play": "https://www.rtlplay.be/",
    "OnDemandKorea": "https://www.ondemandkorea.com/",
    "KlikFilm": "https://www.klikfilm.com/",
    "TvIgle": "https://www.tvigle.ru/",
    "Strim": "https://www.strim.tv/",
    "Film Movement Plus": "https://www.filmmovementplus.com/",
    "Nova Play": "https://www.novaplay.cz/",
    "iQIYI": "https://www.iq.com/",
    "Paramount+ Amazon Channel": "https://www.amazon.com/paramount-plus",
    "MGM+ Amazon Channel": "https://www.amazon.com/mgm-plus",
    "Discovery+ Amazon Channel": "https://www.amazon.com/discovery-plus",
    "Metrograph": "https://metrograph.com/",
    "IFC Amazon Channel": "https://www.amazon.com/ifc",
    "MGM Amazon Channel": "https://www.amazon.com/mgm",
    "TELETOON+ Amazon Channel": "https://www.amazon.com/teletoon-plus",
    "Now TV Cinema": "https://www.nowtv.com/cinema",
    "STV Player": "https://www.stv.tv/",
    "Eros Now Amazon Channel": "https://www.amazon.com/eros-now",
    "Arrow Video Amazon Channel": "https://www.amazon.com/arrow-video",
    "Full Moon Amazon Channel": "https://www.amazon.com/full-moon",
    "Pokémon Amazon Channel": "https://www.amazon.com/pokemon",
    "Shout! Factory Amazon Channel": "https://www.amazon.com/shout-factory",
    "FilmBox Live Amazon Channel": "https://www.amazon.com/filmbox-live",
    "CuriosityStream Amazon Channel": "https://www.amazon.com/curiositystream",
    "DocuBay Amazon Channel": "https://www.amazon.com/docubay",
    "Super Channel Amazon Channel": "https://www.amazon.com/super-channel",
    "StackTV Amazon Channel": "https://www.amazon.com/stacktv",
    "OUTtv Amazon Channel": "https://www.amazon.com/outtv",
    "Love Nature Amazon Channel": "https://www.amazon.com/love-nature",
    "Smithsonian Channel Amazon Channel": "https://www.amazon.com/smithsonian-channel",
    "BBC Earth Amazon Channel": "https://www.amazon.com/bbc-earth",
    "ALLWAYSBLK Amazon Channel": "https://www.amazon.com/allwaysblk",
    "Amazon Prime Video Free with Ads": "https://www.primevideo.com/storefront/free-with-ads",
    "VI movies and tv": "https://www.viaplay.com/",
    "W4free": "https://www.w4free.com/",
    "DRTV": "https://www.dr.dk/drtv",
    "Nordisk Film+": "https://www.nordiskfilmplus.dk/",
    "UPC TV": "https://www.upctv.com/",
    "WeTV": "https://www.wetv.vip/",
    "KKTV": "https://www.kktv.me/",
    "LINE TV": "https://tv.line.me/",
    "Otta": "https://www.otta.com/",
    "Voyo": "https://www.voyo.nova.cz/",
    "Edisonline": "https://www.edisonline.com/",
    "OSN+": "https://www.osnplus.com/",
    "STARZPLAY": "https://www.starzplay.com/",
    "HRTi": "https://www.hrt.hr/rtvs/",
    "Paramount+ Roku Premium Channel": "https://channelstore.roku.com/details/107007/paramount-plus",
    "Starz Roku Premium Channel": "https://channelstore.roku.com/details/100037/starz",
    "AMC+ Roku Premium Channel": "https://channelstore.roku.com/details/106884/amc-plus",
    "MGM Plus Roku Premium Channel": "https://channelstore.roku.com/details/107008/mgm-plus",
    "Pickbox NOW": "https://www.pickboxnow.com/",
    "Public Domain Movies": "https://publicdomainmovies.net/",
    "CineMember": "https://www.cinemember.com/",
    "Nexo Plus": "https://www.nexoplus.com/",
    "STUDIOCANAL PRESENTS Apple TV Channel": "https://tv.apple.com/channel/studiocanal-presents",
    "Eventive": "https://eventive.org/",
    "Filmlegenden Amazon Channel": "https://www.amazon.com/filmlegenden",
    "Cinema of Hearts Amazon Channel": "https://www.amazon.com/cinema-of-hearts",
    "Bloody Movies Amazon Channel": "https://www.amazon.com/bloody-movies",
    "Film Total Amazon Channel": "https://www.amazon.com/film-total",
    "Looke Amazon Channel": "https://www.amazon.com/looke",
    "FlixOlé Amazon Channel": "https://www.amazon.com/flixole",
    "Cine+ OCS Amazon Channel": "https://www.amazon.com/cine-plus-ocs",
    "Home of Horror Amazon Channel": "https://www.amazon.com/home-of-horror",
    "Arthouse CNMA Amazon Channel": "https://www.amazon.com/arthouse-cnma",
    "ShortsTV Amazon Channel": "https://www.amazon.com/shortstv",
    "TVCortos Amazon Channel": "https://www.amazon.com/tvcortos",
    "Pongalo Amazon Channel": "https://www.amazon.com/pongalo",
    "Play Suisse": "https://www.playsuisse.ch/",
    "Cultpix": "https://www.cultpix.com/",
    "Turk On Video Amazon Channel": "https://www.amazon.com/turk-on-video",
    "Serially": "https://www.serially.tv/",
    "meJane": "https://www.mejane.com/",
    "FilmBox+": "https://www.filmboxplus.com/",
    "iBAKATV": "https://www.ibakatv.com/",
    "IROKOTV": "https://www.irokotv.com/",
    "Hollywood Suite Amazon Channel": "https://www.amazon.com/hollywood-suite",
    "Moviedome Plus Amazon Channel": "https://www.amazon.com/moviedome-plus",
    "Aniverse Amazon Channel": "https://www.amazon.com/aniverse",
    "Superfresh Amazon Channel": "https://www.amazon.com/superfresh",
    "Comedy Central Plus Amazon Channel": "https://www.amazon.com/comedy-central-plus",
    "BluTV Amazon Channel": "https://www.amazon.com/blutv",
    "GRJNGO Amazon Channel": "https://www.amazon.com/grjngo",
    "MTV Plus Amazon Channel": "https://www.amazon.com/mtv-plus",
    "RTL Passion Amazon Channel": "https://www.amazon.com/rtl-passion",
    "Silverline Amazon Channel": "https://www.amazon.com/silverline",
    "Shahid VIP": "https://shahid.mbc.net/",
    "Acontra Plus": "https://www.acontraplus.com/",
    "ESPN": "https://www.espn.com/",
    "AVA VOBB": "https://www.ava-vobb.com/",
    "AVA HBZ": "https://www.ava-hbz.com/",
    "AVA CSAL": "https://www.ava-csal.com/",
    "AVA BGB": "https://www.ava-bgb.com/",
    "Infinity Selection Amazon Channel": "https://www.amazon.com/infinityselection",
    "CG Collection Amazon channel": "https://www.amazon.com/cgcollection",
    "iWonder Full Amazon channel": "https://www.amazon.com/iwonderfull",
    "Full Action Amazon Channel": "https://www.amazon.com/fullaction",
    "Cine Comico Amazon Channel": "https://www.amazon.com/cinecomico",
    "Universcine Amazon Channel": "https://www.amazon.com/universcine",
    "Action Max Amazon Channel": "https://www.amazon.com/actionmax",
    "Filmo Amazon Channel": "https://www.amazon.com/filmo",
    "Insomnia Amazon Channel": "https://www.amazon.com/insomnia",
    "Shadowz Amazon Channel": "https://www.amazon.com/shadowz",
    "INA madelen Amazon Channel": "https://www.amazon.com/inamadelen",
    "Benshi Amazon Channel": "https://www.amazon.com/benshi",
    "Planet Horror Amazon Channel": "https://www.amazon.com/planethorror",
    "Dizi Amazon Channel": "https://www.amazon.com/dizi",
    "Acontra Plus Amazon Channel": "https://www.amazon.com/acontraplus",
    "Historia y Actualidad Amazon Channel": "https://www.amazon.com/historiayactualidad",
    "Icon Film Amazon Channel": "https://www.amazon.com/icon-film",
    "Curzon Amazon Channel": "https://www.amazon.com/curzon",
    "Hallmark TV Amazon Channel": "https://www.amazon.com/hallmark-tv",
    "Studiocanal Presents Amazon Channel": "https://www.amazon.com/studiocanalpresents",
    "TOD": "https://www.tod.com/",
    "TF1+": "https://www.tf1.fr/tf1-plus",
    "filmingo": "https://www.filmingo.com/",
    "Sooner Amazon Channel": "https://www.amazon.com/sooner",
    "Yorck on Demand": "https://www.yorck.de/ondemand",
    "ESPN Plus": "https://www.espn.com/espnplus/",
    "Paramount+ with Showtime": "https://www.paramountplus.com/",
    "Takflix": "https://www.takflix.com/",
    "SkyShowtime": "https://www.skyshowtime.com/",
    "Love and Passion Amazon Channel": "https://www.amazon.com/loveandpassion",
    "Klassiki": "https://www.klassiki.com/",
    "Starz Amazon Channel": "https://www.amazon.com/starz",
    "Netflix Standard with Ads": "https://www.netflix.com/",
    "Studiocanal Presents MOVIECULT Amazon Channel": "https://www.amazon.com/studiocanalmoviecult",
    "Studiocanal Presents ALLSTARS Amazon Channel": "https://www.amazon.com/studiocanalallstars",
    "Cohen Media Amazon Channel": "https://www.amazon.com/cohen-media",
    "HBO Max Amazon Channel": "https://www.amazon.com/hbomax",
    "TOD TV": "https://www.tod.com/",
    "Behind the Tree": "https://www.behindthetree.com/",
    "Tivify": "https://www.tivify.com/",
    "Britbox Apple TV Channel": "https://tv.apple.com/channel/britbox",
    "Paramount Plus Apple TV Channel": "https://tv.apple.com/channel/paramount-plus",
    "AMC Plus Apple TV Channel": "https://tv.apple.com/channel/amc-plus",
    "Starz Apple TV Channel": "https://tv.apple.com/channel/starz",
    "Magenta TV": "https://www.telekom.com/en/magenta-tv",
    "Telenet": "https://www.telenet.be/",
    "Univer Video": "https://www.univervideo.com/",
    "Filmow": "https://www.filmow.com.br/",
    "ViX Premium Amazon Channel": "https://www.amazon.com/vix-premium",
    "Runtime": "https://www.runtime.com/",
    "TVING": "https://www.tving.com/",
    "BrutX Amazon Channel": "https://www.amazon.com/brutx",
    "Universal+ Amazon Channel": "https://www.amazon.com/universal-plus",
    "alleskino Amazon Channel": "https://www.amazon.com/alleskino",
    "RTL Crime Amazon Channel": "https://www.amazon.com/rtl-crime",
    "CineAutore Amazon Channel": "https://www.amazon.com/cineautore",
    "Anime Generation Amazon Channel": "https://www.amazon.com/anime-generation",
    "Raro Video Amazon Channel": "https://www.amazon.com/raro-video",
    "MIDNIGHT FACTORY Amazon Channel": "https://www.amazon.com/midnight-factory",
    "Amazon MX Player": "https://www.mxplayer.in/",
    "HBO Max": "https://www.hbomax.com/",
    "ARD Plus": "https://www.ard.de/plus",
    "TV+": "https://www.tvplus.com/",
    "Apollo": "https://www.apollo.tv/",
    "Reserva Imovision": "https://www.imovision.com.br/",
    "Prima Plus": "https://www.primaplus.cz/",
    "Filmtastic bei Canal+": "https://www.canalplus.com/filmtastic",
    "Lepsi TV": "https://www.lepsitv.com/",
    "TV4 Play": "https://www.tv4play.se/",
    "Reveel": "https://www.reveel.com/",
    "ServusTV On": "https://www.servustv.com/on/",
    "Angel Studios": "https://www.watchangel.com/",
    "Cineverse": "https://www.cineverse.com/",
    "AD tv": "https://www.adtv.com/",
    "Midnight Pulp": "https://www.midnightpulp.com/",
    "Allente": "https://www.allente.se/",
    "Xumo Play": "https://www.xumo.tv/",
    "National Geographic": "https://www.nationalgeographic.com/tv/",
    "Molotov TV": "https://www.molotov.tv/",
    "Crunchyroll Amazon Channel": "https://www.amazon.com/crunchyroll",
    "DistroTV": "https://www.distro.tv/",
    "myfilmfriend": "https://www.myfilmfriend.com/",
    "Filmicca": "https://www.filmicca.com/",
    "Outside Watch": "https://www.outside.watch/",
    "NPO Plus": "https://www.npostart.nl/plus",
    "Brollie": "https://www.brollie.com/",
    "ZDF Select Amazon Channel": "https://www.amazon.com/zdf-select",
    "GlewedTV": "https://www.glewedtv.com/",
    "Videoload": "https://www.videoload.com/",
    "TELE 5": "https://www.tele5.de/",
    "MTV Katsomo": "https://www.mtv.fi/katsomo",
    "A&E Crime Central Apple TV Channel": "https://tv.apple.com/channel/ae-crime-central",
    "Acorn TV Apple TV": "https://tv.apple.com/channel/acorn-tv",
    "ALLBLK Apple TV channel": "https://tv.apple.com/channel/allblk",
    "ARD Plus Apple TV channel": "https://tv.apple.com/channel/ard-plus",
    "Arthaus+ Apple TV channel": "https://tv.apple.com/channel/arthaus-plus",
    "BET+  Apple TV channel": "https://tv.apple.com/channel/bet-plus",
    "BFI Player Apple TV Channel": "https://tv.apple.com/channel/bfi-player",
    "Carnegie Hall+ Apple TV Channel": "https://tv.apple.com/channel/carnegie-hall-plus",
    "OUTtv Apple TV Channel": "https://tv.apple.com/channel/outtv",
    "UP Faith & Family Apple TV Channel": "https://tv.apple.com/channel/up-faith-family",
    "Tastemade Apple TV Channel": "https://tv.apple.com/channel/tastemade",
    "Sundance Now Apple TV Channel": "https://tv.apple.com/channel/sundance-now",
    "Shudder Apple TV Channel": "https://tv.apple.com/channel/shudder",
    "ScreenPix Apple TV Channel": "https://tv.apple.com/channel/screenpix",
    "Love Nature Apple TV Channel": "https://tv.apple.com/channel/love-nature",
    "Lionsgate Play Apple TV Channel": "https://tv.apple.com/channel/lionsgate-play",
    "Lifetime Play Apple TV Channel": "https://tv.apple.com/channel/lifetime-play",
    "Lifetime Movie Club Apple TV Channel": "https://tv.apple.com/channel/lifetime-movie-club",
    "IFC Films Unlimited Apple TV Channel": "https://tv.apple.com/channel/ifc-films-unlimited",
    "HISTORY Vault Apple TV Channel": "https://tv.apple.com/channel/history-vault",
    "Hallmark+ Apple TV Channel": "https://tv.apple.com/channel/hallmark-plus",
    "Eros Now Select Apple TV Channel": "https://tv.apple.com/channel/eros-now-select",
    "CuriosityStream Apple TV Channel": "https://tv.apple.com/channel/curiositystream",
    "Cinemax Apple TV Channel": "https://tv.apple.com/channel/cinemax",
    "ALLBLK Amazon channel": "https://www.amazon.com/allblk",
    "ARD Plus Amazon channel": "https://www.amazon.com/ard-plus",
    "UP Faith & Family Amazon Channel": "https://www.amazon.com/up-faith-family",
    "Tastemade Amazon Channel": "https://www.amazon.com/tastemade",
    "ScreenPix Amazon Channel": "https://www.amazon.com/screenpix",
    "Carnegie Hall+ Amazon Channel": "https://www.amazon.com/carnegie-hall-plus",
    "HISTORY Vault Amazon Channel": "https://www.amazon.com/history-vault",
    "Lionsgate Play Amazon Channel": "https://www.amazon.com/lionsgate-play",
    "Lifetime Play Amazon Channel": "https://www.amazon.com/lifetime-play",
    "Wedo TV": "https://www.wedotv.com/",
    "Plex Channel": "https://www.plex.tv/",
    "Troma NOW": "https://www.troma.com/now",
    "KiKA": "https://www.kika.de/",
    "Sony pictures": "https://www.sonypictures.com/",
    "Lifetime Movie Club Amazon Channel": "https://www.amazon.com/lifetime-movie-club",
    "Amazon Prime Video with Ads": "https://www.primevideo.com/storefront/free-with-ads",
    "CANAL+": "https://www.canalplus.com/",
    "Premiery Canal+": "https://www.canalplus.com/premiery",
    "Adrenalina Pura Amazon channel": "https://www.amazon.com/adrenalina-pura",
    "Adrenalina Pura Apple TV channel": "https://tv.apple.com/channel/adrenalina-pura",
    "Far East Amazon Channel": "https://www.amazon.com/far-east",
    "Cinu": "https://www.cinu.com/",
    "BYUtv": "https://www.byutv.org/",
    "AXN Black Amazon Channel": "https://www.amazon.com/axn-black",
    "Kino Film Collection": "https://www.kinofilmcollection.com/",
    "Arthaus+": "https://www.arthausplus.com/",
    "MGM Plus Amazon Channel": "https://www.amazon.com/mgm-plus",
    "MGM+ Apple TV Channel": "https://tv.apple.com/channel/mgm-plus",
    "CG tv": "https://www.cgtv.com/",
    "ORF ON": "https://orf.at/on",
    "ORF KIDS": "https://orf.at/kids",
    "Telecine Amazon Channel": "https://www.amazon.com/telecine",
    "Reserva Imovision Amazon Channel": "https://www.amazon.com/reserva-imovision",
    "Stingray Amazon Channel": "https://www.amazon.com/stingray",
    "CurtaOn Amazon Channel": "https://www.amazon.com/curtaon",
    "Sony One Amazon Channel": "https://www.amazon.com/sony-one",
    "Atresplayer Amazon Channel": "https://www.amazon.com/atresplayer",
    "Vix Gratis Amazon Channel": "https://www.amazon.com/vix-gratis",
    "Gaia Amazon Channel": "https://www.amazon.com/gaia",
    "Cindie Amazon Channel": "https://www.amazon.com/cindie",
    "DocPlay Amazon Channel": "https://www.amazon.com/docplay",
    "Iwonder Amazon Channel": "https://www.amazon.com/iwonder",
    "Rialto Amazon Channel": "https://www.amazon.com/rialto",
    "Anime Digital Network Amazon Channel": "https://www.amazon.com/anime-digital-network",
    "Strand Releasing Amazon Channel": "https://www.amazon.com/strand-releasing",
    "Hoichoi Amazon Channel": "https://www.amazon.com/hoichoi",
    "ManoramaMAX Amazon Channel": "https://www.amazon.com/manoramamax",
    "Chaupal Amazon Channel": "https://www.amazon.com/chaupal",
    "BBC Kids Amazon Channel": "https://www.amazon.com/bbc-kids",
    "Sony Pictures Amazon Channel": "https://www.amazon.com/sony-pictures",
    "Vrott Amazon Channel": "https://www.amazon.com/vrott",
    "Anime Times Amazon Channel": "https://www.amazon.com/anime-times",
    "Museum Tv Amazon Channel": "https://www.amazon.com/museum-tv",
    "NammaFlix Amazon Channel": "https://www.amazon.com/nammaflix",
    "Plaion Pictures": "https://www.plaion-pictures.com/",
    "Toggo": "https://www.toggo.de/",
    "Kixi": "https://www.kixi.tv/",
    "Verleihshop": "https://www.verleihshop.de/",
    "Freenet meinVOD": "https://www.freenet.tv/meinvod",
    "3sat": "https://www.3sat.de/",
    "CDA Premium": "https://www.cda.pl/premium",
    "Akibapass": "https://www.akibapass.com/",
    "NFL Game Pass Amazon Channel": "https://www.amazon.com/nfl-game-pass",
    "Disaster X Amazon Channel": "https://www.amazon.com/disaster-x",
    "Galactic Stream Amazon Channel": "https://www.amazon.com/galactic-stream",
    "BATTLEZONE Amazon Channel": "https://www.amazon.com/battlezone",
    "tabii": "https://www.tabii.tv/",
    "3Cat": "https://www.3cat.com/",
    "FlixHouse": "https://www.flixhouse.com/",
    "Movistar Plus+": "https://www.movistarplus.es/",
    "Apple TV Plus Amazon Channel": "https://www.amazon.com/apple-tv-plus",
    "ASIATIC Amazon Channel": "https://www.amazon.com/asiatic",
    "Auto Motor und Sport Amazon Channel": "https://www.amazon.com/auto-motor-und-sport",
    "AXN White Amazon Channel": "https://www.amazon.com/axn-white",
    "Fix And Foxi Amazon Channel": "https://www.amazon.com/fix-and-foxi",
    "FlimmerkisteTV Amazon Channel": "https://www.amazon.com/flimmerkiste-tv",
    "Franatic Amazon Channel": "https://www.amazon.com/franatic",
    "GEO Television Amazon Channel": "https://www.amazon.com/geo-television",
    "GEO Wild Amazon Channel": "https://www.amazon.com/geo-wild",
    "Good Movies Amazon Channel": "https://www.amazon.com/good-movies",
    "Gute Laune TV Amazon Channel": "https://www.amazon.com/gute-laune-tv",
    "Historama Amazon Channel": "https://www.amazon.com/historama",
    "Kabel Eins Classics Amazon Channel": "https://www.amazon.com/kabel-eins-classics",
    "Kinderwelt Amazon Channel": "https://www.amazon.com/kinderwelt",
    "Kixi Select Amazon Channel": "https://www.amazon.com/kixi-select",
    "Moconomy Amazon Channel": "https://www.amazon.com/moconomy",
    "Netzkino Select Amazon Channel": "https://www.amazon.com/netzkino-select",
    "ProSieben Fun Amazon Channel": "https://www.amazon.com/prosieben-fun",
    "Qello Concerts by Stingray Amazon Channel": "https://www.amazon.com/qello-concerts",
    "Queer Cinemab Amazon Channel": "https://www.amazon.com/queer-cinemab",
    "RTL Living Amazon Channel": "https://www.amazon.com/rtl-living",
    "Sat.1 emotions Amazon Channel": "https://www.amazon.com/sat1-emotions",
    "Spiegel Geschichte Amazon Channel": "https://www.amazon.com/spiegel-geschichte",
    "Sportdigital Amazon Channel": "https://www.amazon.com/sportdigital",
    "Stingray Classica Amazon Channel": "https://www.amazon.com/stingray-classica",
    "Stingray Djazz Amazon Channel": "https://www.amazon.com/stingray-djazz",
    "Stingray Karaoke Amazon Channel": "https://www.amazon.com/stingray-karaoke",
    "Terra X Amazon Channel": "https://www.amazon.com/terra-x",
    "Waidwerk Amazon Channel": "https://www.amazon.com/waidwerk",
    "Wild West Amzon Channel": "https://www.amazon.com/wild-west",
    "Monomax": "https://www.monomax.com/",
    "HBO Max on U-Next": "https://www.unext.jp/",
    "JustWatchTV": "https://www.justwatch.com/",
    "VIVA by videofutur": "https://www.viva-videofutur.com/",
    "Adrenalin Amazon channel": "https://www.amazon.com/adrenalin",
    "Allstars Amazon Channel": "https://www.amazon.com/allstars",
    "Fernsehen mit Herz Amazon Channel": "https://www.amazon.com/fernsehen-mit-herz",
    "Moviecult Amazon Channel": "https://www.amazon.com/moviecult",
    "Redlight Cinema Amazon Channel": "https://www.amazon.com/redlight-cinema",
    "Seven Entertainment Amazon Channel": "https://www.amazon.com/seven-entertainment",
    "Stingray All good vibes Amazon Channel": "https://www.amazon.com/stingray-all-good-vibes",
    "Thrillbox Amazon Channel": "https://www.amazon.com/thrillbox",
    "Viaplay Amazon Channel": "https://www.amazon.com/viaplay",
    "ZDF Krimi Amazon Channel": "https://www.amazon.com/zdf-krimi",
    "ZDFtivi Amazon channel": "https://www.amazon.com/zdftivi",
    "Bergblick Amazon Channel": "https://www.amazon.com/bergblick",
    "ITVX Premium": "https://www.itv.com/itvx",
    "Mercado Play": "https://www.mercadoplay.com/",
    "Paramount Plus Premium": "https://www.paramountplus.com/",
    "Paramount Plus Basic with Ads": "https://www.paramountplus.com/basic-ads/",
    "Premiere Max": "https://www.premieremax.com/",
    "Darkroom": "https://www.darkroom.com/",
    "Channel 4 Plus": "https://www.channel4.com/plus",
    "Acaciatv Amazon Channel": "https://www.amazon.com/acaciatv",
    "Adultswim Amazon Channel": "https://www.amazon.com/adultswim",
    "Alchemiya Amazon Channel": "https://www.amazon.com/alchemiya",
    "All warrior network Amazon Channel": "https://www.amazon.com/all-warrior-network",
    "Amebatv Amazon Channel": "https://www.amazon.com/amebatv",
    "Aspire TV Amazon Channel": "https://www.amazon.com/aspire-tv",
    "BeFit Amazon Channel": "https://www.amazon.com/befit",
    "Best of British Tv Amazon Channel": "https://www.amazon.com/best-of-british-tv",
    "Baeble Amazon Channel": "https://www.amazon.com/baeble",
    "Best Westerns Ever Amazon Channel": "https://www.amazon.com/best-westerns-ever",
    "Broadway HD Amazon Channel": "https://www.amazon.com/broadway-hd",
    "Brown Sugar Amazon Channel": "https://www.amazon.com/brown-sugar",
    "Cartoon Network Amazon Channel": "https://www.amazon.com/cartoon-network",
    "Jolt Film": "https://www.joltfilm.com/",
    "JioHotstar": "https://www.hotstar.com/",
    "Filmelier Plus Amazon Channel": "https://www.amazon.com/filmelier-plus",
    "Filmpalast Amazon Channel": "https://www.amazon.com/filmpalast",
    "Lionsgate+ Amazon Channels": "https://www.amazon.com/lionsgate-plus",
    "GEO Television + Wild Amazon Channel": "https://www.amazon.com/geo-television-wild",
    "Polsat Box Go": "https://www.polsatboxgo.pl/",
    "HBO Max CNN Amazon Channel": "https://www.amazon.com/hbo-max-cnn",
    "The Coda Collection Amazon Channel": "https://www.amazon.com/the-coda-collection",
    "Midnight Pulp Amazon Channel": "https://www.amazon.com/midnight-pulp",
    "Daring Docs Amazon Channel": "https://www.amazon.com/daring-docs",
    "Dekkoo Amazon Channel": "https://www.amazon.com/dekkoo",
    "DocCom Amazon Channel": "https://www.amazon.com/doccom",
    "DocuramaFilms Amazon Channel": "https://www.amazon.com/docurama-films",
    "Dove Amazon Channel": "https://www.amazon.com/dove",
    "Dox Amazon Channel": "https://www.amazon.com/dox",
    "Philo": "https://www.philo.com/",
    "Eagle No Limits Amazon Channel": "https://www.amazon.com/eagle-no-limits",
    "Eagle Magic Amazon Channel": "https://www.amazon.com/eagle-magic",
    "Hidive Amazon Channel": "https://www.amazon.com/hidive",
    "Echoboom Amazon Channel": "https://www.amazon.com/echoboom",
    "Cocina ON Amazon Channel": "https://www.amazon.com/cocina-on",
    "Fear Factory Amazon Channel": "https://www.amazon.com/fear-factory",
    "Film Movement Plus Amazon Channel": "https://www.amazon.com/film-movement-plus",
    "Fitfusion Amazon Channel": "https://www.amazon.com/fitfusion",
    "Food Matters Amazon Channel": "https://www.amazon.com/food-matters",
    "France Channel Amazon Channel": "https://www.amazon.com/france-channel",
    "Fuse+ Amazon Channel": "https://www.amazon.com/fuse-plus",
    "Hi-YAH Amazon Channel": "https://www.amazon.com/hi-yah",
    "Indie Club Amazon Channel": "https://www.amazon.com/indie-club",
    "IndieFlix Shorts Amazon Channel": "https://www.amazon.com/indieflix-shorts",
    "Here TV  Amazon Channel": "https://www.amazon.com/here-tv",
    "IndiePix Unlimited Amazon Channel": "https://www.amazon.com/indiepix-unlimited",
    "Doki Amazon Channel": "https://www.amazon.com/doki",
    "Fawesome": "https://www.fawesome.tv/",
    "Eternal Family": "https://www.eternalfamily.tv/",
    "Magenta TV+": "https://www.telekom.com/en/magenta-tv",
    "Kartoon Channel Amazon Channel": "https://www.amazon.com/kartoon-channel",
    "Kidstream Amazon Channel": "https://www.amazon.com/kidstream",
    "Magnolia Selects Amazon Channel": "https://www.amazon.com/magnolia-selects",
    "Monsters and Nightmares Amazon Channel": "https://www.amazon.com/monsters-and-nightmares",
    "Marquee TV Amazon Channel": "https://www.amazon.com/marquee-tv",
    "Outside TV Features Amzon Channel": "https://www.amazon.com/outside-tv-features",
    "Passionflix Amazon Channel": "https://www.amazon.com/passionflix",
    "Pinoy Box Office Amazon Channel": "https://www.amazon.com/pinoy-box-office",
    "PBS America Amazon Channel": "https://www.amazon.com/pbs-america",
    "PBS Documentaries Amazon Channel": "https://www.amazon.com/pbs-documentaries",
    "PBS Living Amazon Channel": "https://www.amazon.com/pbs-living",
    "PixL Amazon Channel": "https://www.amazon.com/pixl",
    "Great American Pure Flix Amazon Channel": "https://www.amazon.com/great-american-pure-flix",
    "Revry Amazon Channel": "https://www.amazon.com/revry",
    "Ryan and Friends Plus Amazon Channel": "https://www.amazon.com/ryan-and-friends-plus",
    "ZenLIFE by Stingray Amazon Channel": "https://www.amazon.com/zenlife-by-stingray",
    "Demand Africa Amazon Channel": "https://www.amazon.com/demand-africa",
    "The Surf Network Amazon Channel": "https://www.amazon.com/the-surf-network",
    "Toku Amazon Channel": "https://www.amazon.com/toku",
    "MovieSphere+ Amazon Channel": "https://www.amazon.com/moviesphere-plus",
    "True Royalty Amazon Channel": "https://www.amazon.com/true-royalty",
    "FUEL TV+ Amazon Channel": "https://www.amazon.com/fuel-tv-plus",
    "BongFlix Amazon Channel": "https://www.amazon.com/bongflix",
    "Dreamscape Kids Amazon Channel": "https://www.amazon.com/dreamscape-kids",
    "Green Planet Stream Amazon Channel": "https://www.amazon.com/green-planet-stream",
    "Yoga and Fitness TV Amazon channel": "https://www.amazon.com/yoga-and-fitness-tv",
    "Vemox Cine Amazon Channel": "https://www.amazon.com/vemox-cine",
    "Warriors and Gangsters Amazon Channel": "https://www.amazon.com/warriors-and-gangsters",
    "Xive TV Documentaries Amazon Channel": "https://www.amazon.com/xive-tv-documentaries",
    "XLTV Amazon Channel": "https://www.amazon.com/xltv",
    "Docsville Amazon Channel": "https://www.amazon.com/docsville",
    "Yipee Kids TV Amazon Channel": "https://www.amazon.com/yipee-kids-tv",
    "HBO Max  Amazon Channel": "https://www.amazon.com/hbo-max",
    "Paramount+ Originals Amazon Channel": "https://www.amazon.com/paramount-originals",
    "Paramount+ MTV Amazon Channel": "https://www.amazon.com/paramount-mtv",
    "FOUND TV": "https://www.found.tv/",
    "Stupid Co": "https://www.stupidco.com/",
    "Gaiam TV Yoga & Fit": "https://www.gaiamtv.com/",
    "CineMix+ Amazon Channel": "https://www.amazon.com/cinemix-plus",
    "MYmovies One": "https://www.mymovies.one/",
    "ABC On Demand Amazon Channel": "https://www.amazon.com/abc-on-demand",
    "Asian Drama Channel Amazon Channel": "https://www.amazon.com/asian-drama-channel",
    "Asia Premium Amazon Channel": "https://www.amazon.com/asia-premium",
    "Bloome plus Amazon Channel": "https://www.amazon.com/bloome-plus",
    "Box Brazil Play Amazon Channel": "https://www.amazon.com/box-brazil-play",
    "KADOKAWA channel Amazon Channel": "https://www.amazon.com/kadokawa-channel",
    "Channel K Amazon Channel": "https://www.amazon.com/channel-k",
    "Channel Kyofu Amazon Channel": "https://www.amazon.com/channel-kyofu",
    "Cinefil Wow Plus Amazon Channel": "https://www.amazon.com/cinefil-wow-plus",
    "dAnime Amazon Channel": "https://www.amazon.com/danime",
    "FOD Channel Amazon Channel": "https://www.amazon.com/fod-channel",
    "Indie Films by Realto Amazon Channel": "https://www.amazon.com/indie-films-by-realto",
    "Jidiaigeki Senmon Channel Amazon Channel": "https://www.amazon.com/jidiaigeki-senmon",
    "kino films+ Amazon Channel": "https://www.amazon.com/kino-films-plus",
    "Korean Drama Channel Amazon Channel": "https://www.amazon.com/korean-drama-channel",
    "Lemino Select Amazon Channel": "https://www.amazon.com/lemino-select",
    "NECO Plus Amazon Channel": "https://www.amazon.com/neco-plus",
    "MY HERO Amazon Channel": "https://www.amazon.com/my-hero",
    "NHK Kodomo Park Amazon Channel": "https://www.amazon.com/nhk-kodomo-park",
    "Nihon Eiga Net Amazon Channel": "https://www.amazon.com/nihon-eiga-net",
    "Plus GAGA Amazon Channel": "https://www.amazon.com/plus-gaga",
    "Plus Shochiku Amazon Channel": "https://www.amazon.com/plus-shochiku",
    "Having fun with Shimajiro Amazon Channel": "https://www.amazon.com/shimajiro",
    "BS10 STAR CHANNEL EX Amazon Channel": "https://www.amazon.com/bs10-star-channel-ex",
    "TELESA Amazon Channel": "https://www.amazon.com/telesa",
    "Toei Animation Channel  Amazon Channel": "https://www.amazon.com/toei-animation",
    "Toei On Demand Amazon Channel": "https://www.amazon.com/toei-on-demand",
    "Super Channel Plus": "https://www.superchannel.com/plus",
    "Made in Europe Amazon Channel": "https://www.amazon.com/made-in-europe",
    "YouTube TV": "https://tv.youtube.com/",
    "NFDC Amazon Channel": "https://www.amazon.com/nfdc",
    "Mosaik Amazon Channel": "https://www.amazon.com/mosaik",
    "Mometu": "https://www.mometu.com/",
    "Djangowestern Amazon Channel": "https://www.amazon.com/djangowestern",
    "France TV Amazon Channel": "https://www.amazon.com/france-tv",
    "Oneplay": "https://www.oneplay.tv/",
    "IFI@Home": "https://www.ifi.ie/ifi-at-home/",
    "On Air": "https://www.onair.com/",
    "Bloodstream": "https://www.bloodstream.com/",
    "Cinobo": "https://www.cinobo.com/",
    "Gullimax Amazon Channel": "https://www.amazon.com/gullimax",
    "AMC Channels Amazon Channel": "https://www.amazon.com/amc-channels",
    "Tentkotta": "https://www.tentkotta.com/",
    "MovieMe": "https://www.movieme.com/",
    "Queens club Amazon Channel": "https://www.amazon.com/queens-club",
}